name: CI

on:
  push: ~
  pull_request: ~

jobs:
  build-test:
    name: Run tests on ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - uses: NWBY/pest-action@v1

